version: '3.8'

services:

  blogservice:
    build:
      context: ./blogservice
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVICE_NAME=BlogService
      - PORT=8080
    depends_on:
      - blogservice_db

  blogservice_db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=blogservice_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - blogservice_db_data:/var/lib/postgresql/data
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure


  authservice:
    build:
      context: ./authservice
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SERVICE_NAME=AuthService
      - PORT=8081
    depends_on:
      - authservice_db
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure


volumes:
  blogservice_db_data:
  authservice_db_data:

networks:
  default:
    name: cloudscript_network
